name: ow-libc

on:
  push:
    paths:
      - 'libc/**'
      - '.github/workflows/ow-libc.yml'
  pull_request:
    paths:
      - 'libc/**'
      - '.github/workflows/ow-libc.yml'

jobs:
  build:

    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - runner: ubuntu-latest
          arch: x64
        - runner: macos-13
          arch: x64
        - runner: macos-14
          arch: arm64

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Open Watcom setup
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0-64"
      - name: checkout ELKS
        uses: actions/checkout@v4
      - name: build ${{ matrix.runner }}-${{ matrix.arch }}
        run: |
          . ./env.sh
          cd libc
          sh ./ow-libc.sh
          cd ..

