name: ow-libc

on:
  push:
    paths:
      - 'libc/**'
      - '.github/workflows/ow-libc.yml'
  pull_request:
    paths:
      - 'libc/**'
      - '.github/workflows/ow-libc.yml'

jobs:
  build:

    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macos-13
          - macos-14
        version:
          - "2.0-64"

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Open Watcom setup
        uses: open-watcom/setup-watcom@v0
        with:
          version: ${{ matrix.version }}
      - name: checkout ELKS
        uses: actions/checkout@v2
      - name: build
        run: |
          . ./env.sh
          cd libc
          sh ./ow-libc.sh
          cd ..

